/*
 * Dhanraj Hardware Stores
 *
 * Dhanraj Hardware Stores APIs
 *
 * API version: 1.0.0
 * Contact: viveks.singh@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/dhs/",
		Index,
	},

	Route{
		"AddCustomer",
		strings.ToUpper("Post"),
		"/v1/dhs/bp",
		AddCustomer,
	},

	Route{
		"DeleteBusinessPartner",
		strings.ToUpper("Delete"),
		"/v1/dhs/bp/{bpid}",
		DeleteBusinessPartner,
	},

	Route{
		"GetBusinessPartnerById",
		strings.ToUpper("Get"),
		"/v1/dhs/bp/{bpid}",
		GetBusinessPartnerById,
	},

	Route{
		"GetBusinessPartners",
		strings.ToUpper("Get"),
		"/v1/dhs/bp",
		GetBusinessPartners,
	},

	Route{
		"UpdateCustomer",
		strings.ToUpper("Put"),
		"/v1/dhs/bp/{bpid}",
		UpdateCustomer,
	},

	Route{
		"AddSaleOrderToBusinessPartner",
		strings.ToUpper("Post"),
		"/v1/dhs/bp/{bpid}/saleorder",
		AddSaleOrderToBusinessPartner,
	},

	Route{
		"DeleteOrderOfBusinessPartner",
		strings.ToUpper("Delete"),
		"/v1/dhs/bp/{bpid}/saleorder/{saleorderid}",
		DeleteOrderOfBusinessPartner,
	},

	Route{
		"GetSaleOrderOfBusinessPartner",
		strings.ToUpper("Get"),
		"/v1/dhs/bp/{bpid}/saleorder/{saleorderid}",
		GetSaleOrderOfBusinessPartner,
	},

	Route{
		"GetSaleOrdersForBusinessPartner",
		strings.ToUpper("Get"),
		"/v1/dhs/bp/{bpid}/saleorder",
		GetSaleOrdersForBusinessPartner,
	},

	Route{
		"UpdateSaleOrderOfBusinessPartner",
		strings.ToUpper("Put"),
		"/v1/dhs/bp/{bpid}/saleorder/{saleorderid}",
		UpdateSaleOrderOfBusinessPartner,
	},
}
